/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobiregdesktop;

/**
 *
 * @author Bartosz Bem (bemolx)
 */
public class LogInReg extends javax.swing.JPanel {

    /**
     * Creates new form LogInReg
     */
    public LogInReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logoText2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoText1 = new javax.swing.JLabel();
        logoText3 = new javax.swing.JLabel();
        logoText4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoText5 = new javax.swing.JLabel();
        logoText6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(67, 122, 159));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 247, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoText.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        logoText.setForeground(new java.awt.Color(67, 122, 159));
        logoText.setIcon(new javax.swing.ImageIcon("D:\\mobireg app\\logo_mobireg.png")); // NOI18N
        jPanel1.add(logoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(67, 122, 159));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 160, 10));

        logoText2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        logoText2.setForeground(new java.awt.Color(67, 122, 159));
        logoText2.setText("Desktop v0.0.1-alpha");
        jPanel1.add(logoText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel2.setForeground(new java.awt.Color(67, 122, 159));
        jLabel2.setText("by Bartosz Bem 2017");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 590));

        logoText1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        logoText1.setForeground(new java.awt.Color(255, 255, 255));
        logoText1.setText("Adres e-dziennika");
        add(logoText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        logoText3.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        logoText3.setForeground(new java.awt.Color(255, 255, 255));
        logoText3.setText("Logowanie");
        add(logoText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        logoText4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        logoText4.setForeground(new java.awt.Color(255, 255, 255));
        logoText4.setText("LOGIN");
        add(logoText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 220, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 220, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 220, 30));

        jCheckBox1.setBackground(new java.awt.Color(67, 122, 159));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Zapamiętaj mnie");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        jLabel1.setForeground(new java.awt.Color(67, 122, 159));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bemolx\\Downloads\\settings_white_18x18.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 88, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoText5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        logoText5.setForeground(new java.awt.Color(255, 255, 255));
        logoText5.setText("Zaloguj");
        jPanel2.add(logoText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 60, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 130, 40));

        logoText6.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        logoText6.setForeground(new java.awt.Color(255, 255, 255));
        logoText6.setText("HASŁO");
        add(logoText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        jTextField1.setBackground(new java.awt.Color(67, 122, 159));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("np. jkowalski");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 220, -1));

        jPasswordField1.setBackground(new java.awt.Color(67, 122, 159));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 220, -1));

        jTextField2.setBackground(new java.awt.Color(67, 122, 159));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("np. https://mobireg.pl/kod-szkoly");
        jTextField2.setBorder(null);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel logoText;
    private javax.swing.JLabel logoText1;
    private javax.swing.JLabel logoText2;
    private javax.swing.JLabel logoText3;
    private javax.swing.JLabel logoText4;
    private javax.swing.JLabel logoText5;
    private javax.swing.JLabel logoText6;
    // End of variables declaration//GEN-END:variables
}
